/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
	export interface GlobalComponents {
		Avatar: typeof import("./../components/layout/components/header/components/Avatar.vue")["default"]
		BaseEcharts: typeof import("./../components/pageEcharts/src/BaseEcharts.vue")["default"]
		BreadCrumb: typeof import("./../components/layout/components/header/components/BreadCrumb.vue")["default"]
		Card: typeof import("./../components/card/Card.vue")["default"]
		ChangeLanguage: typeof import("./../components/changeLanguage/index.vue")["default"]
		ColSetting: typeof import("./../components/proTable/components/ColSetting.vue")["default"]
		Company: typeof import("./../components/layout/components/header/components/Company.vue")["default"]
		Footer: typeof import("./../components/layout/components/footer/index.vue")["default"]
		FormDialog: typeof import("./../components/proTable/components/FormDialog.vue")["default"]
		Grid: typeof import("./../components/grid/index.vue")["default"]
		GridItem: typeof import("./../components/grid/components/GridItem.vue")["default"]
		HeaderLeft: typeof import("./../components/layout/components/header/HeaderLeft.vue")["default"]
		HeaderRight: typeof import("./../components/layout/components/header/HeaderRight.vue")["default"]
		IEpCircleCheckFilled: typeof import("~icons/ep/circle-check-filled")["default"]
		Info: typeof import("./../components/layout/components/header/components/Info.vue")["default"]
		Layout: typeof import("./../components/layout/index.vue")["default"]
		LayoutClassic: typeof import("./../components/layout/layoutClassic/index.vue")["default"]
		LayoutColumns: typeof import("./../components/layout/layoutColumns/index.vue")["default"]
		LayoutTransverse: typeof import("./../components/layout/layoutTransverse/index.vue")["default"]
		LayoutVertical: typeof import("./../components/layout/layoutVertical/index.vue")["default"]
		LineEcharts: typeof import("./../components/pageEcharts/src/LineEcharts.vue")["default"]
		Main: typeof import("./../components/layout/components/main/Main.vue")["default"]
		MoreButton: typeof import("./../components/layout/components/tabs/components/MoreButton.vue")["default"]
		Pagination: typeof import("./../components/proTable/components/Pagination.vue")["default"]
		PieEcharts: typeof import("./../components/pageEcharts/src/PieEcharts.vue")["default"]
		ProForm: typeof import("./../components/proForm/index.vue")["default"]
		ProFormItem: typeof import("./../components/proForm/components/ProFormItem.vue")["default"]
		ProTable: typeof import("./../components/proTable/index.vue")["default"]
		RoseEcharts: typeof import("./../components/pageEcharts/src/RoseEcharts.vue")["default"]
		RouterLink: typeof import("vue-router")["RouterLink"]
		RouterView: typeof import("vue-router")["RouterView"]
		Screenfull: typeof import("./../components/layout/components/header/components/Screenfull.vue")["default"]
		SearchForm: typeof import("./../components/searchForm/index.vue")["default"]
		SearchFormItem: typeof import("./../components/searchForm/components/SearchFormItem.vue")["default"]
		Select: typeof import("./../components/layout/components/header/components/Select.vue")["default"]
		Setting: typeof import("./../components/layout/components/header/components/Setting.vue")["default"]
		SvgIcon: typeof import("./../components/svgIcon/index.vue")["default"]
		TableColumn: typeof import("./../components/proTable/components/TableColumn.vue")["default"]
		Tabs: typeof import("./../components/layout/components/tabs/index.vue")["default"]
		TreeFilter: typeof import("./../components/treeFilter/index.vue")["default"]
		TreeMenu: typeof import("./../components/layout/components/sidebar/TreeMenu.vue")["default"]
		WangEditor: typeof import("./../components/wangEditor/index.vue")["default"]
	}
}
